title: Hello Github
author: aubs
email: ad.r.sl213@domain.com
mah first page

# social links
twitter_username: none
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
